function locationsUK(loc){
    var newLocation = "";
    if(loc.indexOf("London")>-1){newLocation = "London, GB";}
    if(loc.indexOf("Edinburgh")>-1){newLocation = "Edinburgh, Scotland, GB";}
    if(loc.indexOf("Liverpool")>-1){newLocation = "Liverpool, England, GB";}
    if(loc.indexOf("Bristol")>-1){newLocation = "Bristol, England, GB";}
    if(loc.indexOf("Birmingham")>-1){newLocation = "Birmingham, England, GB";}
    if(loc.indexOf("Glasgow")>-1){newLocation = "Glasgow, Scotland, GB";}
    if(loc.indexOf("Manchester")>-1){newLocation = "Manchester, England, GB";}
    if(loc.indexOf("York")>-1){newLocation = "York, England, GB";}
    if(loc.indexOf("Newcastle upon Tyne")>-1){newLocation = "Newcastle upon Tyne, England, GB";}
    if(loc.indexOf("Oxford")>-1){newLocation = "Oxford, England, GB";}
    if(loc.indexOf("Cardiff")>-1){newLocation = "Cardiff, Wales, GB";}
    if(loc.indexOf("Leeds")>-1){newLocation = "Leeds, England, GB";}
    if(loc.indexOf("Bath")>-1){newLocation = "Bath, England, GB";}
    if(loc.indexOf("Brighton")>-1){newLocation = "Brighton, England, GB";}
    if(loc.indexOf("Sheffield")>-1){newLocation = "Sheffield, England, GB";}
    if(loc.indexOf("Kingston upon Hull")>-1){newLocation = "Kingston upon Hull, England, GB";}
    if(loc.indexOf("Cambridge")>-1){newLocation = "Cambridge, England, GB";}
    if(loc.indexOf("Norwich")>-1){newLocation = "Norwich, England, GB";}
    if(loc.indexOf("Portsmouth")>-1){newLocation = "Portsmouth, England, GB";}
    if(loc.indexOf("Aberdeen")>-1){newLocation = "Aberdeen, Scotland, GB";}
    if(loc.indexOf("Leicester")>-1){newLocation = "Leicester, GB";}
    if(loc.indexOf("Nottingham")>-1){newLocation = "Nottingham, England, GB";}
    if(loc.indexOf("Plymouth")>-1){newLocation = "Plymouth, England, GB";}
    if(loc.indexOf("Coventry")>-1){newLocation = "Coventry, England, GB";}
    if(loc.indexOf("Chester")>-1){newLocation = "Chester, England, GB";}
    if(loc.indexOf("Durham")>-1){newLocation = "Durham, England, GB";}
    if(loc.indexOf("Exeter")>-1){newLocation = "Exeter, England, GB";}
    if(loc.indexOf("Southampton")>-1){newLocation = "Southampton, England, GB";}
    if(loc.indexOf("Peterborough")>-1){newLocation = "Peterborough, England, GB";}
    if(loc.indexOf("Stoke-on-Trent")>-1){newLocation = "Stoke-on-Trent, England, GB";}
    if(loc.indexOf("Lincoln")>-1){newLocation = "Lincoln, England, GB";}
    if(loc.indexOf("Salisbury")>-1){newLocation = "Salisbury, England, GB";}
    if(loc.indexOf("Bradford")>-1){newLocation = "Bradford, England, GB";}
    if(loc.indexOf("Sunderland")>-1){newLocation = "Sunderland, England, GB";}
    if(loc.indexOf("Dundee")>-1){newLocation = "Dundee, Scotland, GB";}
    if(loc.indexOf("Reading")>-1){newLocation = "Reading, England, GB";}
    if(loc.indexOf("Preston")>-1){newLocation = "Preston, England, GB";}
    if(loc.indexOf("Wolverhampton")>-1){newLocation = "Wolverhampton, England, GB";}
    if(loc.indexOf("Greater Manchester")>-1){newLocation = "Greater Manchester, England, GB";}
    if(loc.indexOf("Swansea")>-1){newLocation = "Swansea, Swansea, GB";}
    if(loc.indexOf("Derby")>-1){newLocation = "Derby, England, GB";}
    if(loc.indexOf("Canterbury")>-1){newLocation = "Canterbury, England, GB";}
    if(loc.indexOf("Luton")>-1){newLocation = "Luton, England, GB";}
    if(loc.indexOf("Bournemouth")>-1){newLocation = "Bournemouth, England, GB";}
    if(loc.indexOf("Blackpool")>-1){newLocation = "Blackpool, England, GB";}
    if(loc.indexOf("Gloucester")>-1){newLocation = "Gloucester, England, GB";}
    if(loc.indexOf("City of Westminster")>-1){newLocation = "City of Westminster, England, GB";}
    if(loc.indexOf("Winchester")>-1){newLocation = "Winchester, England, GB";}
    if(loc.indexOf("Carlisle")>-1){newLocation = "Carlisle, England, GB";}
    if(loc.indexOf("Milton Keynes")>-1){newLocation = "Milton Keynes, England, GB";}
    if(loc.indexOf("Bedford")>-1){newLocation = "Bedford, GB";}
    if(loc.indexOf("Colchester")>-1){newLocation = "Colchester, GB";}
    if(loc.indexOf("Ipswich")>-1){newLocation = "Ipswich, England, GB";}
    if(loc.indexOf("Norwich ")>-1){newLocation = "Norwich, GB";}
    if(loc.indexOf("Peterborough")>-1){newLocation = "Peterborough, England, GB";}
    if(loc.indexOf("Dunfermline")>-1){newLocation = "Dunfermline, Scotland, GB";}
    if(loc.indexOf("Basildon")>-1){newLocation = "Basildon, England, GB";}
    if(loc.indexOf("Hampshire")>-1){newLocation = "Hampshire, GB";}
    if(loc.indexOf("Essex")>-1){newLocation = "Essex, GB";}
    if(loc.indexOf("Wellington")>-1){newLocation = "Wellington, England, GB";}
    if(loc.indexOf("Milton")>-1){newLocation = "Milton, Cambridgeshire, United Kingdom";}
    if(loc.indexOf("Wantage")>-1){newLocation = "Wantage, England, GB";}
    if(loc.indexOf("Norfolk")>-1){newLocation = "Norfolk, England, GB";}
    if(loc.indexOf("Peebles")>-1){newLocation = "Peebles, Scotland, GB";}
    if(loc.indexOf("Evesham")>-1){newLocation = "Evesham, England, GB";}
    if(loc.indexOf("Bridgewater")>-1){newLocation = "Bridgewater, England, GB";}
    if(loc.indexOf("Rochester")>-1){newLocation = "Rochester, England, GB";}
    if(loc.indexOf("Burgess Hill")>-1){newLocation = "Burgess Hill, England, GB";}
    if(loc.indexOf("Tilbury Dock")>-1){newLocation = "Tilbury Dock, GB";}
    if(loc.indexOf("Guildford")>-1){newLocation = "Guildford, GB";}

    return newLocation;
}